micronaut:
  application:
    name: demo
elasticsearch:
  httpHosts: http://localhost:9200
imdb:
  key: imdb
  basePath: src/main/resources/imdb/
  fileName: title.basics.tsv
  indexName: _index_config.json
  bulk: 5000
  total: 7662622
reducedImdb:
  key: test
  basePath: src/test/resources/test/
  fileName: test.basics.tsv
  indexName: index.json
  bulk: 5000
  total: 5000
